---
name: Test Terraform
on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: string
        default: self-hosted
        required: false
      terraform-image:
        type: string
        default: eu.gcr.io/stuttgart-things/sthings-terraform:1.7.5
        required: false

      
jobs:
  Test-Aws-Connection:
    runs-on: ${{ inputs.runs-on }}
    container:
      image: ${{ inputs.terraform-image }}
    environment: k8s
    continue-on-error: false
    steps:
      - run: |
          terraform --version
          aws --version