---
name: Test Terraform Creation
on:
  workflow_dispatch:
    inputs:
      image-version:
        type: string
        default: eu.gcr.io/stuttgart-things/sthings-terraform:1.7.5
        required: false
      runs-on:
        type: string
        required: false
        default: ghr-aws-ec2-vm-sthings-cicd
      environment-name:
        type: string
        required: true
        default: k8s
      aws-region:
        type: string
        required: true
        default: eu-west-1

jobs:
  test-terraform-creation:
    runs-on: ${{ inputs.runs-on }} #ghr-aws-ec2-vm-sthings-cicd
    container:
      image: ${{ inputs.image-version }} #eu.gcr.io/stuttgart-things/sthings-terraform:1.7.5
    environment: ${{ inputs.environment-name }}
    continue-on-error: false
    steps:
      - name: Check versions
        id: check
        run: |
          terraform --version
          aws --version
      - name: Set and test aws credentials
        id: creds
        run: |
          aws configure set region ${{ inputs.aws-region }}
          echo ${{ secrets.AWS_CONFIG }} | base64 -d > ~/.aws/credentials
          aws configure list
          aws sts get-caller-identity
