---
name: Test Terraform
on:
  workflow_dispatch:
    inputs:
      image-version:
        type: string
        default: eu.gcr.io/stuttgart-things/sthings-terraform:1.7.5

jobs:
  Test-Aws-Connection:
    runs-on: ghr-aws-ec2-vm-sthings-cicd
    container:
      image: ${{ inputs.image-version }} #eu.gcr.io/stuttgart-things/sthings-terraform:1.7.5
    environment: k8s
    continue-on-error: false
    steps:
      - run: |
          terraform --version
          aws --version