---
name: Test Terraform
on:
  workflow_dispatch:
    inputs:
      image-version:
        type: string
        default: eu.gcr.io/stuttgart-things/sthings-terraform:1.7.5
        required: false
      runs-on:
        type: string
        required: false
        default: ghr-aws-ec2-vm-sthings-cicd
      #environment-name:
      #  type: string
      #  required: true
      #  default: k8s

jobs:
  Test-Aws-Connection:
    runs-on: ${{ inputs.runs-on }} #ghr-aws-ec2-vm-sthings-cicd
    container:
      image: ${{ inputs.image-version }} #eu.gcr.io/stuttgart-things/sthings-terraform:1.7.5
    environment: k8s
    env:
      AWS_CONFIG_FILE: $HOME/.aws/credentials
    continue-on-error: false
    steps:
      - run: |
          terraform --version
          aws --version
      - name: create credentials file
        run: |
          mkdir -p ${AWS_CONFIG_FILE}
          echo ${{ secrets.AWS_CONFIG }} | base64 -d > ${AWS_CONFIG_FILE}
      - name: view the content credentials file
        run: cat ~/.aws/credentials
        
          
