---
name: Validate Terraform
on:
  push:
    branches:
    - main
    - feature/*
    - fix/*
  pull_request:
    branches:
    - main
    - feature/*
    - fix/*
  workflow_dispatch:

jobs:
  validate-terraform:
    name: Valdiate
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-terraform.yaml@main
    with:
      environment-name: k8s
      runs-on: arc-runner-scale-set-aws-ec2-vm
      terraform-version: 1.6
      tflint-version: "v0.50.0"
      continue-error: false
